import type { EffectConfig, EffectId } from "./types";

export const EFFECTS: Record<EffectId, EffectConfig> = {
  fire: {
    id: "fire",
    displayName: "Fire",
    slot: "element",
    durationMs: 10_000,
    maxStacks: 3,
    replacesSameSlot: true,
    visual: {
      mainColorToken: "color.element.fire.main",
      coreColorToken: "color.element.fire.core",
      icon: "flame",
      pattern: "flame",
      trailPreset: "fireTongues",
      impactPreset: "fireFan",
      residuePreset: "embers",
    },
    gameplay: {
      tickCount: 3,
      tickIntervalMs: 260,
      damagePerTick: 0.34,
    },
  },
  electric: {
    id: "electric",
    displayName: "Electric",
    slot: "element",
    durationMs: 10_000,
    replacesSameSlot: true,
    visual: {
      mainColorToken: "color.element.electric.main",
      coreColorToken: "color.element.electric.core",
      icon: "bolt",
      pattern: "zigzag",
      trailPreset: "electricSparks",
      impactPreset: "electricBranch",
      residuePreset: "chargeGlow",
    },
    gameplay: {
      maxChains: 3,
      chainRadius: 210,
      chainDamageMultiplier: 0.62,
      conductorBonusChains: 1,
    },
  },
  piercing: {
    id: "piercing",
    displayName: "Piercing",
    slot: "trajectory",
    durationMs: 9_000,
    replacesSameSlot: true,
    visual: {
      mainColorToken: "color.element.piercing.main",
      coreColorToken: "color.element.piercing.core",
      icon: "spear",
      pattern: "spear",
      trailPreset: "cutLine",
      impactPreset: "crossSlash",
      residuePreset: "cutResidue",
    },
    gameplay: {
      charges: 4,
      damageFalloffPerHit: 0.08,
      minimumDamageMultiplier: 0.7,
    },
  },
  explosion: {
    id: "explosion",
    displayName: "Explosion",
    slot: "element",
    durationMs: 8_000,
    replacesSameSlot: true,
    visual: {
      mainColorToken: "color.element.explosion.main",
      coreColorToken: "color.element.explosion.core",
      icon: "burst",
      pattern: "radial",
      trailPreset: "hotEmbers",
      impactPreset: "shockwave",
      residuePreset: "smokeDebris",
    },
    gameplay: {
      radius: 155,
      edgeDamageMultiplier: 0.35,
      maxChainDepth: 1,
      maxChainTargetsPerFrame: 24,
    },
  },
  multiball: {
    id: "multiball",
    displayName: "Multi Ball",
    slot: "multiplier",
    replacesSameSlot: true,
    visual: {
      mainColorToken: "color.element.arcane.main",
      coreColorToken: "color.element.arcane.core",
      icon: "multi-orb",
      pattern: "orbital",
      trailPreset: "phaseAfterimage",
      impactPreset: "orbitalSplit",
    },
    gameplay: {
      spawnCount: 2,
      splitAngleDegrees: 18,
      maxActiveBalls: 8,
      inheritedDurationMultiplier: 0.7,
    },
  },
  ice: {
    id: "ice",
    displayName: "Ice",
    slot: "element",
    durationMs: 10_000,
    replacesSameSlot: true,
    visual: {
      mainColorToken: "color.element.ice.main",
      coreColorToken: "color.element.ice.core",
      icon: "snowflake",
      pattern: "crystal",
      trailPreset: "iceCrystals",
      impactPreset: "crystalBloom",
      residuePreset: "frostCracks",
    },
    gameplay: {
      brittleDurationMs: 2_200,
      brittleDamageMultiplier: 1.6,
      movingObjectSlowMultiplier: 0.65,
    },
  },
  homing: {
    id: "homing",
    displayName: "Homing",
    slot: "trajectory",
    durationMs: 8_000,
    replacesSameSlot: true,
    visual: {
      mainColorToken: "color.element.arcane.main",
      coreColorToken: "color.element.arcane.core",
      icon: "target-curve",
      pattern: "target",
      trailPreset: "homingCurve",
      impactPreset: "spiralConverge",
    },
    gameplay: {
      turnRateDegreesPerSecond: 100,
      launchGraceMs: 180,
      piercingCombinationMultiplier: 0.7,
    },
  },
  laser: {
    id: "laser",
    displayName: "Laser",
    slot: "utility",
    durationMs: 8_000,
    replacesSameSlot: false,
    visual: {
      mainColorToken: "color.element.laser.main",
      coreColorToken: "color.element.laser.core",
      icon: "beam",
      pattern: "beam",
      trailPreset: "laserCharge",
      impactPreset: "laserImpact",
    },
    gameplay: {
      fireIntervalMs: 240,
      baseDamage: 1,
      bossDamageMultiplier: 0.45,
    },
  },
  shield: {
    id: "shield",
    displayName: "Shield",
    slot: "utility",
    replacesSameSlot: false,
    visual: {
      mainColorToken: "color.element.shield.main",
      coreColorToken: "color.element.shield.core",
      icon: "hex-shield",
      pattern: "hex",
      trailPreset: "shieldIdle",
      impactPreset: "shieldRipple",
    },
    gameplay: {
      charges: 2,
      reflectedSpeedMultiplier: 0.92,
    },
  },
  slowTime: {
    id: "slowTime",
    displayName: "Slow Time",
    slot: "utility",
    durationMs: 4_500,
    replacesSameSlot: false,
    visual: {
      mainColorToken: "color.element.time.main",
      coreColorToken: "color.element.time.core",
      icon: "clock-ring",
      pattern: "clock",
      trailPreset: "timeAfterimage",
      impactPreset: "timeRipple",
    },
    gameplay: {
      timeScale: 0.62,
      refreshDurationOnReapply: true,
      allowScaleStacking: false,
    },
  },
};

export const EFFECT_IDS = Object.keys(EFFECTS) as EffectId[];
